// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLPb14aMBdayxymT2RPLQu28Q2pNybUt0',
    appId: '1:166289098859:android:a01565f2fe3ff9cc1ac92e',
    messagingSenderId: '166289098859',
    projectId: 'aikeenpark',
    storageBucket: 'aikeenpark.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXgdL6JI-8JiO43W54iWe7XSjk20dubw',
    appId: '1:166289098859:ios:3546cbe32e5b51c91ac92e',
    messagingSenderId: '166289098859',
    projectId: 'aikeenpark',
    storageBucket: 'aikeenpark.appspot.com',
    iosClientId: '166289098859-0rb40vem7f70ji913di6f62cb0l42b6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.aikeenPark',
  );
}
